### PR TITLE
Change to synaptic data handling

### LINKED ISSUE #29: Error running examples
Hello Everibody,
    after the installation of  Nupic_sudio on Ubuntu 12.04, I tried to run the given examples. For each one I can initialize the nework with no problem, but if I try to do 1 step prediction (but for n-steps is the same) nothing changes in the net.

Looking at the console, when I click the prediction button I see this message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/ui/main_form.py", line 509, in __buttonStepHTM_Click
    Global.project.network.nextStep()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/network.py", line 68, in nextStep
    node.nextStep()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/node_region.py", line 277, in nextStep
    self.updateTemporalElements()
  File "/usr/local/lib/python2.7/dist-packages/nupic_studio-1.1.2-py2.7.egg/nupic_studio/htm/node_region.py", line 472, in updateTemporalElements
    (_, sourceCellAbsIdx, permanence) = self.temporalPooler.connections.dataForSynapse(synIdx)
TypeError: 'SynapseData' object is not iterable

Any idea?

### PR DESCRIPTION
**Pull request by rcrowder**
Fixes #29

### CODE REVIEW

**Comment by rhyolight** [comment]
@david-ragazzi It has been 6 months since Travis-CI was green...

**Comment by david-ragazzi** [comment]
Thanks @rcrowder ! I'll merge this as error is related to OS X build and not to your changes!

**Comment by rcrowder** [comment]
@david-ragazzi Muito obrigado.

**Comment by david-ragazzi** [comment]
@rcrowder Eu que agradeço! 😄

**Pull request merged**
